---
title: Python 정리 #3
date: 2021-06-28 23:17:32 +09:00
modified: 2021-06-28 23:17:32 +09:00
comments: true
tags: [TIL, 데청캠, python, 2021, 2106, study, basics]
description: python basics #3
---

> *<span style="color:grey">[python documentation](https://docs.python.org/)</span>*

> *<span style="color:grey">Python 3.9에서의 정리</span>*
# 복합문 (Compound Statements)

## if문
---
```python
if 표현식:
    수행할 작업
```

- if에 조건식이 아니라, 어떠한 표현식이 들어가도 상관없다
- 존재론적인 관점에서 있으면, True / 없으면, False를 의미한다.

```python
if float('nan'):
    print(1)
if float('inf'):
    print(2)
if lambda x:x+1:
    print(3)
if print:
    print(4)
if None:
    print(5)
# 1 2 3 4
# 배열이 비어있으면 false 반환, 이는 array, string, set 등 사용 가능하다
# 즉 원소가 하나라도 있다면 참이다
```

## else문
---
else도 3가지 용법이 있다
1. `for ~ else`
    ```python
    for i in range(5):
        print(i)
    else:
        print('end')
    ```
    중단되지 않으면, 즉 올바르게 반복이 끝나면 else 구문 실행
2. `while ~ else`
    ```python
    a = 10
    while a>5:
        print(a)
        a-=1
    else:
        print('end)
    ```
3. `try except구문 else`

- else는 flow control에 다 붙을 수 있다
 
- 아주 많은 task를 성공적으로 마무리 된다면 출력하는 방식

## for, while문
---

while문은 쉽게 무한루프를 만들 수 있도록 해준다

반복문은 실수가 가장 많이 생기는 부분

for문은 iterable한 반복문

```python
for i in:
```
membership변수
in 다음에는 iterable한 collection이 나온다.



### in 다음 문자열
```python
4 in 'abc' # ERROR
'a' in 'abc'
```

문자열이 오는 경우에는 앞에 무조건 문자열이여야 함.


### in 다음 dictionary
```python
1 in {'a':1, 'b':2} # returns False
```

key만 체크를 하기 때문에 False를 반환

### Iterator
>list, enumerate, ... iterable하다

이는 conatiner와 유사한데, container의 경우 원소를 여러개 가질 수 있는애

atomic과 반개 개념
- iterable은 여러개를 가지는데 하나씩 순회할 수 있는 container를 뜻함
    - 정확하겐 iterator가 될 수 있는 애
    - data를 한개씩 순차적으로 뽑는 애
- 실제 내부적으로는, 아래참조

```python
def x():
    for i in 1,2,3:
        print(i)

import dis
dis.dis(x)

"""
  2           0 LOAD_CONST               1 ((1, 2, 3))
              2 GET_ITER
        >>    4 FOR_ITER                12 (to 18)
              6 STORE_FAST               0 (i)

  3           8 LOAD_GLOBAL              0 (print)
             10 LOAD_FAST                0 (i)
             12 CALL_FUNCTION            1
             14 POP_TOP
             16 JUMP_ABSOLUTE            4
        >>   18 LOAD_CONST               0 (None)
             20 RETURN_VALUE
"""
```

- iteration 활용 예시
```python
t = iter((1,2,3))
next(t) # 1
next(t) # 2

from itertools import cycle
s = cycle([1,2,3])
print(next(s))  # 1
print(next(s))  # 2
print(next(s))  # 3
print(next(s))  # 1
```
#### 반복문, iterator와 in 구문 정리

```python
print("---- set ----")
for i in {3,5,3,4,2,1,2,3}: # 정렬도 하고 중복제거
    print(i)
print("---- dict keys ----")
for i in {'a':1, 'b':2}: # key만 순회
    print(i)
print("--- dict values ----")
for i in {'a':1, 'b':2}.values(): # value만 순회 / .items를 이용하면 tuple반환
    print(i)
```

# 예외 처리

python은 EAFP(easier to ask for forgiveness than permission)의 코딩 스타일을 가진다.
- 허락보다 용서가 쉽다
- 에러나면 에러처리 하시죠 방식이다

```python
if a==1:
    ~
# LBYL(look before you leap)
# 많은 if문의 존재로 특정되며, 보기와 뛰기 간의 race condition을 만들 수 있다.
a = 1
b = 3 if a>3 else 1 # 할당 가능, expression, 삼항연산자
# 결과 : b = 1
```

code 짜놓고 틀렸을 때 고치자

```python
a = 1
print(c)
"""
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-193-2b66fd261ee5> in <module>
----> 1 print(c)

NameError: name 'c' is not defined
"""
```

위의 작업을 수행한다면 NameError라는 에러를 찾을 수 있는데,

이 에러는 어디에서 온 것일까?

- LEGB에서 B(Bulitin)에 존재한다.
- builtin은 처음 python을 수행하였을 때 자동으로 실행되는 부분이다

```python
import builtins
'print' in dir(builtins) # True
dir(builtins)            # 을 통해서 확인이 가능하다.
                         # Error들도 여기에 정의되어있다.
```

## 예외를 처리하는 방법 
> 크게 2 종류로 나눌 수 있다.
1. 에러가 나더라도 남은 작업을 모두 수행을 하는 방식
    - 중간에 실수가 나오더라도 마저 수행하는 것이 중요할때
2. 에러가 발생하거나, 결과 값이 치명적인 문제를 발생시켜 스스로 에러를 발생시키는 상황

일반적으로 초급 프로그래머는 디버깅을 진행하면서 `print`구문을 이용해서 디버깅을 하게 되는데, 이 경우에는 실제 구동되는 부분과 디버깅의 구분이 없다는 단점이 존재하게 된다.

그래서 예외처리 방식인, `assert`, `raise`, `try` 같은 구문을 이용한다.

### 내가 원하는 값이 나오지 않을 때 강제로 에러를 호출할 때 사용하는 방식 2가지

#### Assert
---
`assert "조건", "메세지"`

- 값을 알고 있다는 가정에서 사용
- `assert a==2, "*error message*"`
- True가 아니면 AssertionError 발생 설명
- print와 달리 코드에 영향을 주지 않는다.
- 원하는 결과값이 아니라면 프로그램의 구동이 중단된다


#### Raise
---
```python
x = 1
if x==1:
    raise Exception('this will be error!')#NameError
else:
       print('a')
        
# NameError를 발생
```
- 강제로 특정 에러를 발생시킨다.
- Error의 부모는 누구인가?
    - 부모를 찾을 때는 "에러".\_\_bases\_\_를 사용 / s는 다중상속을 지원하는 파이썬 특성상 들어감
    - MRO라는 규칙에 의해서 첫번째 부모를 나타냄
    
### 에러가 발생하더라도 프로그램이 계속 작동을 하게 만들어주는 방식

#### Try
---
```python
try : 
    print(notCalledBefore)
    1/0
except NameError:
    print("name err")
except ZeroDivisionError:
    print('div 0')
except:
    print('err..')
else:
    print('b')
# name err이 출력된다.
# 그 밑에 있는 try문들은 수행이 되지 않는다. 1/0에서 발생되는 에러는 발생할일이 없다.
```

- else는 선택사항이다. try except만 사용해도 괜찮다. -> **모든 else는 선택사항**
    - if문에서 별일 없을때, try에서 별일 없을때, for에서 별일 없을 때 발생
- except는 여러개 사용 가능
- `except:` 는 `except Exception:` 과 같다
- ```python
    except Exception as e:
    print(e)
    # 위 경우에는 exception type을 알려줌
  ```

예시
```python
x = 1
if x==1:
    raise Exception('this will be error!')
else:
       print('a')
"""
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-208-8e7658d97cef> in <module>
      1 x = 1
      2 if x==1:
----> 3     raise Exception('this will be error!')#NameError
      4 else:
      5        print('a')

Exception: this will be error!
"""
```
<br>

<br>

<br>

*<span style="color:grey">21-06-28 - 문서 생성</span>*
